Switch from toml to tomli/tomllib
seddonym/import-linter pull request #152
Opened 2022-12-29 23:53 UTC by mwgamble

The toml package is unmaintained, so it was appropriate to move away from it as a dependency. The tomli package is the most appropriate alternative, because it was incorporated into the Python standard library as of Python 3.11, under the name tomllib.

Due to the prevalence of tomli as a compulsory dependency of many other Python code quality tools (such as black, mypy, pytest and pylint), there's a big chance that users will already have it installed if they're using Import Linter. Therefore, tomli is now a compulsory dependency (if you're using versions of Python earlier than 3.11).

This change has several benefits:

- Reduces the overall number of dependencies in the average Python application
- Removes a dependency on an unmaintained project
- Reduces the complexity of configuration-related testing
- Greatly simplifies the tox configuration

Fixes #146

2023-01-02 10:10 UTC, seddonym requested changes
Thanks for this, I agree with your reasoning. A nice simplification.

If you have a chance would you mind adding your name to the `AUTHORS.rst` (assuming you'd like to) and also a line at the top of the CHANGELOG, along the lines of:

```

latest
------

* Switch from optional dependency of toml to required dependency of tomli for Python versions < 3.11.
```

2023-01-03 04:50 UTC, mwgamble commented
@seddonym I've updated the PR as requested :+1:

2023-01-09 20:59 UTC, mwgamble commented
@seddonym Any chance this PR could be merged? That way my grimp types update is based off this work.

2023-01-10 11:24 UTC, seddonym approved these changes

2023-01-10 11:25 UTC, merged

2023-01-10 11:25 UTC, seddonym commented
Done, apologies for the delay. Thanks again!

2023-01-10 11:38 UTC, seddonym commented
Hmm, interestingly the merge has caused master mypy checks to fail, because it's now installing the latest version of Grimp. I wonder if we should pin the dependencies on Grimp in the toxfile?

Anyway it sounds like your types update will address these issues, so I'll leave it to you if that's ok?

2023-01-10 11:53 UTC, mwgamble commented
Yep, it's gonna be easiest to just wait a bit for my next PR :+1:

2023-01-10 11:57 UTC, mwgamble commented
Speaking of: https://github.com/seddonym/import-linter/pull/153

By the way I think these failures could have been avoided if the intermediary protocol didn't exist (a la #148)